name: correa_tours
description: Una nueva app Flutter

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  carousel_slider: ^5.0.0
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.3.0
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  youtube_player_flutter: ^9.1.1
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_lints: ^3.0.1

flutter_native_splash:
  image: assets/logo.png
  android_gravity: center
  ios_content_mode: center
  color: "#ffffff"
  fullscreen: true
  android: true
  ios: true


flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
